### ISSUE TITLE
Foodcritic error FC109

### ISSUE THREAD

**Issue by pollymerkner** [chef-cookbooks/logrotate#130]
FC109: Use platform-specific package resources instead of provider property: ./recipes/default.rb:23.  Code from the recipe is:

package node['logrotate']['package']['name'] do
  provider node['logrotate']['package']['provider'] if node['logrotate']['package']['provider']
  source node['logrotate']['package']['source'] if node['logrotate']['package']['source']
  version node['logrotate']['package']['version'] if node['logrotate']['package']['version']
  action node['logrotate']['package']['action']
end

**Comment by shoekstra** [comment]
Hey @pollymerkner - this has been addressed in #128.
